cidenet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('talentoh.urls')),
]

talentoh/urls.py
from django.urls import path

from . import views

app_name="talentoh"

urlpatterns = [
    path('', views.consultar_empleados, name='consultar_empleados'),
    path('formulario_actualizar/<int:id>/', views.FormularioActualizar, name='formulario_actualizar'),
    path('actualizar/<int:id>/', views.actualizar, name='actualizar'),
    path('EmpleadoEliminar/<int:id>/', views.EmpleadoEliminar, name='EmpleadoEliminar'),
    path('crear_empleado/', views.crear_empleado, name='crear_empleado'),
    path('validarNumero/', views.validarNumero, name='validarNumero'),
]

talentoh/models.py
from django.db import models

# Create your models here.

class Empleados(models.Model):
    primer_apellido = models.CharField(max_length = 20, null=False, blank=False)
    segundo_apellido = models.CharField(max_length = 20, null=False, blank=False)
    primer_nombre = models.CharField(max_length = 20, null=False, blank=False)
    otros_nombres = models.CharField(max_length = 20,  blank=True)
    PAISEMPLEO = (
        ('Colombia', 'Colombia'),
        ('EE.UU', 'EE.UU'),  
    )
    pais_empleo = models.CharField(max_length=30, choices=PAISEMPLEO, null=False, blank=False)
    
    numero_identificacion = models.CharField(max_length=20, null=False, blank=False, unique=True)
    TIPO = (
        ('Cédula de Ciudadanía', 'Cédula de Ciudadanía'),
        ('Cédula de Extranjería', 'Cédula de Extranjería'),
        ('Pasaporte', 'Pasaporte'),
        ('Permiso Especial', 'Permiso Especial'),
    )
    tipo_identificacion = models.CharField(max_length=21, choices=TIPO, null=False, blank=False)
    Correo_Electronico=models.EmailField(max_length=300, null=False, blank=False)
    fecha_ingreso =  models.DateTimeField(auto_now=False, auto_now_add=False, null=False, blank=False)
    AREA = (
        ('Administración', 'Administración'),
        ('Financiera', 'Financiera'),
        ('Compras', 'Compras'),
        ('Infraestructura', 'Infraestructura'),
        ('Operación', 'Operación'),
        ('Talento Humano', 'Talento Humano'),
        ('Servicios Varios', 'Servicios Varios'),
    )
    area = models.CharField(max_length=30, choices=AREA, null=False, blank=False)
    
    ESTADO = (
        ('Activo', 'Activo'),
        ('Inactivo', 'Inactivo'),
    )
    estado = models.CharField(max_length=30, choices=ESTADO, default='1', null=False, blank=False)
    fecha_registro = models.DateTimeField(auto_now=False, auto_now_add=False, blank=False)
    
    class Meta:
        verbose_name="Empleado"
        verbose_name_plural="Empleados"
    
    def __str__(self):
        return f"Nombre: {self.primer_nombre} - Apellido: {self.primer_apellido}"

talentoh/forms.py
from django import forms
from django.forms import fields
from .models import Empleados

class EmpleadosForm(forms.ModelForm):
    class Meta:
        model = Empleados
        fields = '__all__'

talentoh/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Empleados

# Create your views here.
from django.http import HttpResponse

def consultar_empleados(request):
    q = Empleados.objects.all()
    contexto = {'datos': q}
    return render(request, 'talentoh/index.html', contexto)

def FormularioActualizar(request, id):
    if id == 0:
        q = {"dato": 0}
    else:
        q = Empleados.objects.get(pk = id)
    contexto = { "dato": q }
    return render(request, 'talentoh/formulario_actualizar.html', contexto)

def crear_empleado(request):
    
    primer_apellido = request.POST['primer_apellido'].upper()
    segundo_apellido = request.POST['segundo_apellido'].upper()
    primer_nombre = request.POST['primer_nombre'].upper()
    otros_nombres = request.POST['otros_nombres'].upper()
    pais_empleo = request.POST['pais_empleo']
    tipo_identificacion = request.POST['tipo_identificacion']
    numero_identificacion = request.POST['numero_identificacion']
    fecha_ingreso = request.POST['fecha_ingreso']
    area = request.POST['area']
    estado = request.POST['estado']
    fecha_registro = request.POST['fecha_registro']
    empleado = Empleados(primer_apellido=primer_apellido, segundo_apellido=segundo_apellido, 
                         primer_nombre= primer_nombre, otros_nombres=otros_nombres, pais_empleo=pais_empleo, 
                         tipo_identificacion=tipo_identificacion, numero_identificacion=numero_identificacion, 
                         fecha_ingreso=fecha_ingreso
                         , area=area, estado=estado, fecha_registro=fecha_registro )
    
    empleado.save()
    id= Empleados.objects.latest("id").pk
    q = Empleados.objects.get(pk = id)
    if q.pais_empleo == "Colombia":
        q.Correo_Electronico= primer_nombre+"."+primer_apellido+"."+str(id)+"@CIDENET.COM.CO"
    else:
        q.Correo_Electronico= primer_nombre+"."+primer_apellido+"."+str(id)+"@CIDENET.COM.US    "
    q.save()
    return HttpResponseRedirect(reverse('talentoh:consultar_empleados', args=() ))

def actualizar(request, id):
    q = Empleados.objects.get(pk = id)

    q.primer_apellido = request.POST['primer_apellido']
    q.segundo_apellido = request.POST['segundo_apellido']
    q.primer_nombre = request.POST['primer_nombre']
    q.otros_nombres = request.POST['otros_nombres']
    q.pais_empleo = request.POST['pais_empleo']
    q.tipo_identificacion = request.POST['tipo_identificacion']
    q.numero_identificacion = request.POST['numero_identificacion']
    q.fecha_ingreso = request.POST['fecha_ingreso']
    q.area = request.POST['area']
    q.estado = request.POST['estado']
    q.save()
    return HttpResponseRedirect(reverse('talentoh:consultar_empleados', args=() ))

def EmpleadoEliminar(request, id):
    q = Empleados.objects.get(pk = id)
    q.delete()
    return HttpResponseRedirect(reverse('talentoh:consultar_empleados', args=() ))

def validarNumero(request):
    empleado = Empleados.objects.get(numero_identificacion=request.POST['numero_identificacion']).pk
    return HttpResponse(empleado>0)
    

talentoh/templates/talentoh/formulario_actualizar.html
{% extends "talentoh/index.html" %} 
{% load static %} 
{% block content %} 
{% if dato.id %}

<h1>Actualizar</h1>
{% else %}
<h1>Crear</h1>
{% endif %} {% csrf_token %}
<input id="empleadoId" type="hidden" name="id" value="{{ dato.id }}" /><br />
Primer apellido:
<input
  style="text-transform: uppercase"
  maxlength="20"
  onkeypress="return check(event)"
  class="form-control"
  name="primer_apellido"
  value="{{ dato.primer_apellido }}"
  id="primer_apellido"
/><br />
Segundo apellido:
<input
  style="text-transform: uppercase"
  maxlength="20"
  onkeypress="return check(event)"
  class="form-control"
  name="segundo_apellido"
  value="{{ dato.segundo_apellido }}"
  id="segundo_apellido"
/><br />
Primer nombre:
<input
  style="text-transform: uppercase"
  maxlength="20"
  onkeypress="return check(event)"
  class="form-control"
  name="primer_nombre"
  value="{{ dato.primer_nombre }}"
  id="primer_nombre"
/><br />
Otros nombres:
<input
  style="text-transform: uppercase"
  maxlength="50"
  onkeypress="return check(event)"
  class="form-control"
  name="otros_nombres"
  value="{{ dato.otros_nombres }}"
  id="otros_nombres"
/><br />
Pais Empleo:
<select
  class="form-control"
  name="pais_empleo"
  value="{{ dato.pais_empleo }}"
  id="pais_empleo"
>
  <option value="Colombia">Colombia</option>
  <option value="EE.UU">EE.UU</option>
</select>
<br />
Tipo identificación:
<select
  class="form-control"
  name="tipo_identificacion"
  value="{{ dato.tipo_identificacion }}"
  id="tipo_identificacion"
>
  <option value="Cédula de Ciudadanía">Cédula de Ciudadanía</option>
  <option value="Cédula de Extranjería">Cédula de Extranjería</option>
  <option value="Pasaporte">Pasaporte</option>
  <option value="Permiso Especial">Permiso Especial</option>
</select>
<br />
Número identificación:
<input
  onblur="validarNumero()"
  class="form-control"
  name="numero_identificacion"
  value="{{ dato.numero_identificacion }}"
  id="numero_identificacion"
/><br />
Correo:
<input
  class="form-control"
  name="Correo_Electronico"
  value="{{ dato.Correo_Electronico }}"
  id="Correo_Electronico"
  disabled
/><br />
Fecha de ingreso:
<input
  class="form-control"
  type="datetime-local"
  name="fecha_ingreso"
  value="{{ dato.fecha_ingreso }}"
  id="fecha_ingreso"
/><br />
Área:
<select class="form-control" name="area" value="{{ dato.area }}" id="area">
  <option value="Administración">Administración</option>
  <option value="Financiera">Financiera</option>
  <option value="Compras">Compras</option>
  <option value="Infraestructura">Infraestructura</option>
  <option value="Operación">Operación</option>
  <option value="Talento Humano">Talento Humano</option>
  <option value="Servicios Varios">Servicios Varios</option>
</select>
<br />
Estado: {%if dato.id %}
<input
  class="form-control"
  name="estado"
  value="{{ dato.estado }}"
  id="estado"
  disabled
/>
<br />
{%else%}
<input class="form-control" name="estado" value="Activo" id="estado" disabled />
<br />
{% endif%} Fecha de registro: {% if dato.id%}
<input
  class="form-control"
  type="datetime-local"
  name="fecha_registro"
  value="{{ dato.fecha_registro }}"
  id="fecha_registro"
  disabled
/>
<br />
{% else %}
<input
  class="form-control"
  type="datetime-local"
  name="fecha_registro"
  value=""
  id="fecha_registro"
/>
<br />
{%endif%} {% if dato.id %}

<button class="btn btn-primary" onclick="validar({{dato.id}})">
  Actualizar</button
><br />
{% else %}
<button class="btn btn-primary" onclick="validar(0)">Crear</button><br />
{%endif%}
<a href="{% url 'talentoh:consultar_empleados' %}">Volver</a>

<script>
  function pad(num) {
    if (num < 10) {
      return "0" + num;
    } else {
      return num;
    }
  }
  var fecha_registro = "{{dato.fecha_registro|date:'Y-m-d H:i:s'}}";
  fecha_registro = new Date(
    fecha_registro.split(" ")[0] + "T" + fecha_registro.split(" ")[1]
  );
  var fecha_final =
    fecha_registro.getFullYear() +
    "-" +
    pad(fecha_registro.getMonth() + 1) +
    "-" +
    pad(fecha_registro.getDate()) +
    "T" +
    pad(fecha_registro.getHours()) +
    ":" +
    pad(fecha_registro.getMinutes()) +
    ":" +
    pad(fecha_registro.getSeconds());
  document.getElementById("fecha_registro").value = fecha_final;

  var fecha_ingreso = "{{dato.fecha_ingreso|date:'Y-m-d H:i:s'}}";
  fecha_ingreso = new Date(
    fecha_ingreso.split(" ")[0] + "T" + fecha_ingreso.split(" ")[1]
  );
  var fecha_final =
    fecha_ingreso.getFullYear() +
    "-" +
    pad(fecha_ingreso.getMonth() + 1) +
    "-" +
    pad(fecha_ingreso.getDate()) +
    "T" +
    pad(fecha_ingreso.getHours()) +
    ":" +
    pad(fecha_ingreso.getMinutes()) +
    ":" +
    pad(fecha_ingreso.getSeconds());
  document.getElementById("fecha_ingreso").value = fecha_final;

  if ("{{dato.id}}" != "") {
    document.getElementById("area").value = "{{dato.area}}";
    document.getElementById("pais_empleo").value = "{{dato.pais_empleo}}";
  }
</script>
{% endblock %}

talentoh/templates/talentoh/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="{% static 'talentoh/css/bootstrap.min.css' %}"
    />
    <!-- fin Bootstrap CSS -->

    <title>Empleados</title>
  </head>
  <body>
    <img src="{% static 'talentoh/img/cidenet.png' %}" width="20%" />
    <h1>Empleados</h1>
    <br />

    <a
      class="btn btn-info"
      href="{% url 'talentoh:formulario_actualizar' 0 %}"
      role="button"
      >Crear</a
    >

    {% if datos %}
    <!--   Tabla para listar datos de los empleados -->
    <table class="table table-hover">
      <tr>
        <th>Primer Nombre</th>
        <th>Otros Nombres</th>
        <th>Primer apellido</th>
        <th>Segundo apellido</th>
        <th>Tipo de identificación</th>
        <th>Número de identificación</th>
        <th>País del empleo</th>
        <th>Correo electrónico</th>
        <th>Estado</th>
        <th>Fecha registro</th>
        <th>Acciones</th>
      </tr>
      {% for datos in datos %}
      <tr>
        <td>{{datos.primer_nombre}}</td>
        <td>{{datos.otros_nombres}}</td>
        <td>{{datos.primer_apellido}}</td>
        <td>{{datos.segundo_apellido}}</td>
        <td>{{datos.tipo_identificacion}}</td>
        <td>{{datos.numero_identificacion}}</td>
        <td>{{datos.pais_empleo}}</td>
        <td>{{datos.Correo_Electronico}}</td>
        <td>{{datos.estado}}</td>
        <td>{{datos.fecha_registro}}</td>

        <td>
          <a
            class="btn btn-info"
            href="{% url 'talentoh:formulario_actualizar' datos.id %}"
            role="button"
            >Editar empleado</a
          >
          <a
            class="btn btn-danger"
            onclick="eliminarEmpleado('{% url 'talentoh:EmpleadoEliminar' datos.id %}')"
            role="button"
            >Eliminar</a
          >
        </td>
      </tr>
      {% endfor %}
    </table>

    {% endif %}
    <div class="container row">{% block content %} {% endblock %}</div>
    <!--   Bootstrap JS Jquery -->

    <script src="{% static 'talentoh/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'talentoh/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'talentoh/js/libreria.js' %}"></script>
  </body>
</html>